[package]
name = "Toycoin"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../../aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../aptos-move/framework/aptos-token" }
# MoveStdlib = { local = "../../aptos-move/framework/move-stdlib" }
# Marketplace = { local = "../marketplace" }