[package]
name = "Marketplace"
version = "0.0.0"

[addresses]
marketplace = "0xf5b9d6f01a99e74c790e2f330c092fa05455a8193f1dfc1b113ecc54d067afe1"

[dependencies]
AptosFramework = { local = "../../aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../aptos-move/framework/aptos-token" }
AptosTokenObjects = { local = "../../aptos-move/framework/aptos-token-objects" }
