[package]
name = "Tokens"
version = "0.0.0"

[addresses]
tokens = "_"

[dependencies]
AptosFramework = { local = "../../aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../aptos-move/framework/aptos-token" }